
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Tue Jan 18 02:32:51 CET 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 22;
  public static final int READ = 18;
  public static final int MOREEQUAL = 32;
  public static final int PLUS = 25;
  public static final int OR = 23;
  public static final int INT = 12;
  public static final int NOTEQUAL = 30;
  public static final int WHILE = 17;
  public static final int CHAR = 13;
  public static final int SEMI = 8;
  public static final int LEFTPAR = 3;
  public static final int RIGHTPAR = 4;
  public static final int LESSEQUAL = 28;
  public static final int WRITE = 19;
  public static final int ID = 11;
  public static final int DO = 16;
  public static final int EQUALS = 29;
  public static final int COMMA = 9;
  public static final int LESSTHAN = 27;
  public static final int EOF = 0;
  public static final int MAIN = 10;
  public static final int DIV = 24;
  public static final int MORETHAN = 31;
  public static final int DOTDOT = 7;
  public static final int MINUS = 26;
  public static final int CONST = 20;
  public static final int error = 1;
  public static final int ASSIGN = 2;
  public static final int BOOL = 15;
  public static final int REAL = 14;
  public static final int MUL = 21;
  public static final int RIGHTCURLY = 6;
  public static final int LEFTCURLY = 5;
}

